language: java

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew
 - export JAVA8_home=$JAVA_HOME

script:
 - jdk_switcher use oraclejdk7
 - export JAVA7_home=$JAVA_HOME
 - jdk_switcher use oraclejdk8
 - ./gradlew build test