language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

env:
  global:
    - JAVA7_HOME=/usr/lib/jvm/java-8-oracle
    - JAVA8_HOME=/usr/lib/jvm/java-8-oracle

before_install:
  - chmod +x gradlew

script: ./gradlew build test

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export TAG=$(git log -1 | grep -Eo 'tag: ([0-9\.]+)' | cut -d" " -f2)
  - if [ -n "$TAG" ]; then echo "$TAG">>.version && git commit -am "Prepare release $TAG" && git tag $TAG && git push origin $TAG && git push origin master; fi

deploy:
  skip_cleanup: true
  provider: releases
  on:
    branch: master

notifications:
  email: false