language: java

jdk:
 - oraclejdk8

env:
 - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
 - JAVA8_HOME=/usr/lib/jvm/java-8-oracle

before_install:
 - chmod +x gradlew

script:
 - jdk_switcher use oraclejdk7
 - echo $JAVA_HOME
 - jdk_switcher use oraclejdk8
 - echo $JAVA_HOME
 - ./gradlew build test