language: java

jdk:
  - oraclejdk8

env:
  global:
    - JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - JAVA8_HOME=/usr/lib/jvm/java-8-oracle

before_install:
  - chmod +x gradlew

script: ./gradlew build test