language: java

jdk:
 - oraclejdk8
 - oraclejdk7

before_install:
 - chmod +x gradlew
 - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
 - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
 - echo $JAVA7_HOME
 - echo $JAVA8_HOME
 - echo $JAVA_HOME

script:
 - ./gradlew build test